# Series 클래스

In [8]:
import pandas as pd

In [9]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [10]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [11]:
print(s.values)

[1 3 5 7 9]


In [13]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index = ["서울", "부산", "인천", "대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [14]:
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='str')


In [15]:
print(s.values)

[9904312 3448737 2890451 2466052]


In [16]:
s.name = "인구"
s.index.name = "도시"
print(s)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [17]:
s.index.name = None
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [18]:
print(pd.Series(range(1, 5)))

0    1
1    2
2    3
3    4
dtype: int64


In [19]:
s = pd.Series(["samsung", 81000])
print(s)

0    samsung
1      81000
dtype: object


In [20]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [21]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [24]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data = data, index = index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [25]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data, index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [26]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data, index = index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [27]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(index = index, data = data)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [30]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [32]:
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [35]:
s2 = s2.fillna(0)
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [36]:
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [37]:
data = {
    "2019-05-31" : 42500,
    "2019-05-30" : 42550,
    "2019-05-29" : 41800,
    "2019-05-28" : 42550,
    "2019-05-27" : 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [38]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [39]:
print(s.index.dtype)

str


In [40]:
print(s.values)

[42500 42550 41800 42550 42650]


# Series indexing

In [43]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index = [1, 2, 3])

print(s1[0])
print(s2[1])

10
10


In [45]:
s3 = Series([10, 20, 30], index = ["a", "b", "c"])
print(s3["a"])

10


In [46]:
print(s3.index[ 0 ])
print(s3.index[ -1 ])

a
c


# Series Slicing

In [47]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index = ["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [48]:
print(s[1:3])

부산    3448737
인천    2890451
dtype: int64


In [49]:
print(s["부산" : "대구"])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [50]:
print(s[1:])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [51]:
print(s[:-1])

서울    9904312
부산    3448737
인천    2890451
dtype: int64


In [52]:
print(s[:2])

서울    9904312
부산    3448737
dtype: int64


In [54]:
s1 = pd.Series(range(3), index=["a", "b", "c"])
s1

a    0
b    1
c    2
dtype: int64

In [55]:
print(s1.a)

0


In [56]:
print(s1["a"])

0


In [57]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index = ["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [58]:
print("대구" in s)

True


In [59]:
print("대전" in s)

False


In [60]:
for key, value in s.items():
    print(f"{key}, {value}")

서울, 9904312
부산, 3448737
인천, 2890451
대구, 2466052


In [63]:
s2 = pd.Series({
    "서울" : 9631482,
    "부산" : 3393191,
    "인천" : 2632035,
    "대전" : 1490158
})
print(s2)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [62]:
s2 = pd.Series({
    "서울" : 9631482,
    "부산" : 3393191,
    "인천" : 2632035,
    "대전" : 1490158
}, index=["부산", "서울","인천","대전"])
print(s2)

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64


In [102]:
from pandas import Series

data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data, index)
s

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64

In [103]:
print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [104]:
print(s.loc["메로나":"구구콘"])

메로나    1000
구구콘    2000
dtype: int64


In [105]:
indice = [0, 2]
print(s.iloc[indice])

메로나     1000
하겐다즈    3000
dtype: int64


In [106]:
print(s.iloc[[0, 2]])

메로나     1000
하겐다즈    3000
dtype: int64


In [107]:
indice = ["메로나", "하겐다즈"]
print(s.loc[indice])
print(s.loc[["메로나", "하겐다즈"]])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [108]:
s.loc["메로나"] = 500 # == s.iloc[0] = 500 == s["메로나"] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [109]:
s.loc["비비빅"] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [110]:
s1 = s.drop("메로나")
print(s1)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [111]:
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


# Series 연산

In [114]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
             index=["서울", "부산", "인천", "대구"])
s2 = pd.Series({
    "서울" : 9631482,
    "부산" : 3393191,
    "인천" : 2632035,
    "대전" : 1490158
}, index=["부산", "서울", "인천", "대전"])
ds = s - s2
print(ds)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [115]:
s3 = s / 1000000
print(s3)

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64


In [117]:
print(s.values, s2.values)
print(s.values - s2.values)

[9904312 3448737 2890451 2466052] [3393191 9631482 2632035 1490158]
[ 6511121 -6182745   258416   975894]


In [118]:
rs = (s - s2) / s2 * 100
print(rs)

대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [119]:
rs = rs[rs.notnull()]
print(rs)

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [120]:
rs["부산"] = 1.63
rs["대구"] = 1.41
print(rs)

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64


In [121]:
del rs["서울"]
print(rs)

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64


In [125]:
from pandas import Series

date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350], index=date)
print(high)
print("-------------")
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
-------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [126]:
diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [128]:
print(diff.max())

800


In [130]:
print(diff.idxmax())

6/4


In [132]:
data = {
    "삼성전자" : "전기, 전자",
    "LG전자" : "전기, 전자",
    "현대차" : "운수장비",
    "NAVER" : "서비스업",
    "카카오" : "서비스업"
}
s = Series(data)
print(s)

삼성전자     전기, 전자
LG전자     전기, 전자
현대차        운수장비
NAVER      서비스업
카카오        서비스업
dtype: str


In [134]:
print(s.unique())

<StringArray>
['전기, 전자', '운수장비', '서비스업']
Length: 3, dtype: str


In [135]:
print(s.value_counts())

전기, 전자    2
서비스업      2
운수장비      1
Name: count, dtype: int64


In [137]:
import pandas as pd
import numpy as np

s = pd.Series(["선화", "강호", np.nan, "소정", "우영"])
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [139]:
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [140]:
s[s.isnull()]

2    NaN
dtype: str

In [141]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: str

In [146]:
def remove_comma(x):
    return int(x.replace(",", ""))

In [147]:
s = Series(["1,234", "5,678", "9,876"])
result = list(s.map(remove_comma))
print(result)

[1234, 5678, 9876]


In [148]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(data, index)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [149]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [150]:
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [151]:
print(s[s > 42000])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [152]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ["000010", "000020", "000030", "000040"]
s = Series(data, index)
print(s)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64


In [154]:
s1 = s.sort_values()
print(s1)

000020     2.0
000010     3.1
000040     5.1
000030    10.1
dtype: float64


In [155]:
s1 = s.sort_values(ascending=False)
print(s1)

000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [156]:
s2 = s.rank()
print(s2)

000010    2.0
000020    1.0
000030    4.0
000040    3.0
dtype: float64


In [158]:
s2 = s.rank(ascending=False)
print(s2)

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64
